### ISSUE TITLE
Checkout of master fails

### ISSUE THREAD

**Issue by jlewin** [mellinoe/Veldrid.TinyDemo#1]
Submodule points at missing Veldrid commit

>error: Server does not allow request for unadvertised object >f0ea88ce51e5f5d6407b44685924010504a290a9

```
$ git submodule update
error: Server does not allow request for unadvertised object f0ea88ce51e5f5d6407b44685924010504a290a9
Fetched in submodule path 'ext/veldrid', but it did not contain f0ea88ce51e5f5d6407b44685924010504a290a9. Direct fetching of that commit failed.
```

**Comment by jlewin** [comment]
I ended up discovering that NeoDemo is more up-to-date and functional but I originally spent a chunk of time failing to get this demo project to run

**Comment by mellinoe** [comment]
@jlewin This repository was an example for an older version of Veldrid, which is more or less obsolete nowadays. https://github.com/mellinoe/veldrid-samples has several up-to-date examples for the current version of Veldrid. I'll make sure to update the information here so that it reflects the fact that it is out of date.

**Comment by jlewin** [comment]
Thanks for the details. My boss was at my desk and we were looking for a quick sample to get Veldrid running to compare to OpenTK, the TinyDemo project came up first in our search results but only proved to be confusing. Veldrid-samples was exactly what we were looking for.
